name: First WF

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: List and read file
          run: | 
            echo "Hi 1st GH action job"
            ls -ltra 
            cat README.md
          shell: bash
        
        - name: Generate ASCII artwork
          run: cowsay -f dragon "Run for cover now" >> dragon.txt
          shell: bash

        - name: upload file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-artifact
            path: dragon.txt


    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 5 seconds
          run: pwd && sleep 5
          shell: bash

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-artifact

        - name: List and read file
          run: pwd && ls -ltra && grep -i "dragon" dragon.txt && ls -ltra
          #shell: bash


    third_job:
        needs: second_job
        runs-on: ubuntu-latest
        steps:

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-artifact

        - name: List and read file
          run: cat dragon.txt && ls -ltra
          shell: bash


