name: Generate ASCII artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay
          run: sudo apt-get install cowsay -y
       
        - name: Generate ASCII artwork
          run: pwd && cowsay -f dragon "Run for cover" >> dragon.txt && pwd && ls -ltra

        # - name: Verify file exists and view
        #   run: pwd && grep -i "dragon" dragon.txt && ls -ltra

        - name: View
          run: pwd && cat dragon.txt && ls -ltra
                      

        - name: List and read file
          run: | 
            echo "Hi 1st GH action job"
            ls -ltra 

