name: Generate ASCII artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: View
          run: pwd && ls -ltra

        - name: Execute script
          run: |
            chmod +x ascii.sh
            ./ascii.sh

        # - name: Install Cowsay
        #   run: sudo apt-get install cowsay -y
       
        - name: Generate ASCII artwork
          run: pwd && cowsay -f dragon "Run for cover" >> dragon.txt && pwd && ls -ltra

        # - name: Verify file exists and view
        #   run: pwd && grep -i "dragon" dragon.txt && ls -ltra

        - name: List and read file
          run: | 
            cat dragon.txt


